### ISSUE TITLE
Add a comparison with pytest-leak-finder

### ISSUE THREAD

**Issue by mgaitan** [maciej-gol/pytest-bisect-tests#2]
Hi, I'm the author of [pytest-leak-finder](https://pypi.org/project/pytest-leak-finder/).  A friend of mine saw this in reddit. It would be a good idea to do a comparison in your README as you did with the other lib. And of course I invite you to unite the effort in a single project!

**Comment by maciej-gol** [comment]
Hey, thanks for reaching out!

From an initial look over your code, I can think of two major differences between our approaches:
* My approach is automatic, vs yours (where you run each step manually)
    * Thus, it is also possible to hook my package in a CI job.
* My approach works with plugins that modify collected items, like (but not only) https://pypi.org/project/pytest-test-groups/
    * This is important, as some CI workflows split the whole suite into separate parts.

Do you see any other major differences?

How would you suggest we could unite the effort? Happy to hear your thoughts!
